import "#/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Header from "#/app/_components/header";
import { TRPCReactProvider } from "#/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<TRPCReactProvider>
					<Header />
					<main className="min-h-screen bg-gray-50">{children}</main>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
